/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanagementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 91870
 */
public class UpdateDetails extends javax.swing.JFrame {
    Connection conn;
    Statement stmt;
    ResultSet rs;
    DefaultTableModel dtm;
    /**
     * Creates new form UpdateDetails
     */
    
    public UpdateDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbEducation.addItem("Diploma");
        cbEducation.addItem("BCA");
        cbEducation.addItem("BA");
        cbEducation.addItem("BSC");
        cbEducation.addItem("BCom");
        cbEducation.addItem("BTech");
        cbEducation.addItem("BBA");
        cbEducation.addItem("MCA");
        cbEducation.addItem("MA");
        cbEducation.addItem("MSC");
        cbEducation.addItem("MComm");
        cbEducation.addItem("MTech");
        cbEducation.addItem("MBA");
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employeesystem","root","vansh");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select EmpId from personalinfo");
            while(rs.next())
            {
                cbId.addItem(rs.getString(1));
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.print(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtDesg = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFather = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAdhar = new javax.swing.JTextField();
        cbEducation = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbId = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFetch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Employee Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 188, 101, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 185, 218, -1));

        jLabel3.setText("D.O.B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 86, -1));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 237, 218, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 299, 86, -1));

        jLabel5.setText("Designation");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 414, 86, -1));

        jLabel6.setText("Email Id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 359, 86, -1));

        jLabel7.setText("Employee Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 465, 86, 29));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 296, 218, -1));
        getContentPane().add(txtDesg, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 411, 218, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 356, 218, -1));

        jLabel8.setText("Father's Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 188, 101, -1));

        jLabel9.setText("Salary");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 240, 101, -1));

        jLabel10.setText("Phone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 299, 101, -1));

        jLabel11.setText("Adhar Number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 414, 101, -1));

        jLabel12.setText("Higher Education");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 359, 101, -1));
        getContentPane().add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 185, 171, -1));
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 237, 171, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 296, 171, -1));
        getContentPane().add(txtAdhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 411, 171, -1));

        getContentPane().add(cbEducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 356, 171, -1));

        jLabel13.setText("Search By Employe Id");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 115, 128, -1));

        cbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdActionPerformed(evt);
            }
        });
        getContentPane().add(cbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 112, 118, -1));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 465, 218, 29));

        jLabel14.setText("Job Post");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 472, 129, 22));
        getContentPane().add(txtJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 472, 171, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        btnUpdate.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE DETAILS");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCancel.setText("GO TO HOME PAGE");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFetch.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnFetch.setText("FETCH");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE EMPLOYEE DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnUpdate)
                        .addGap(83, 83, 83)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void cbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbIdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtFather.setText("");
        txtDOB.setText("");
        txtSalary.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtDesg.setText("");
        txtAdhar.setText("");
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String name,fname,dob,salary,address,phone,email,education,desg,adhar;
        name = txtName.getText();
        fname = txtFather.getText();
        dob = txtDOB.getText();
        salary = txtSalary.getText();
        address = txtAddress.getText();
        phone = txtPhone.getText();
        email = txtEmail.getText();
        education = cbEducation.getSelectedItem().toString();
        desg = txtDesg.getText();
        adhar = txtAdhar.getText();
        String id = cbId.getSelectedItem().toString();
        try
        {
            stmt.executeUpdate("update personalinfo set Name='"+name+"',Father_Name='"+fname+"',DOB='"+dob+"',Salary='"+salary+"',Address='"+address+"',Phone='"+phone+"',Email='"+email
                +"',Education='"+education+"',Designation='"+desg+"',Adhar='"+adhar+"' where EmpId = "+id+"");
            JOptionPane.showMessageDialog(null,"Update Employee Details Successfully","Message Box",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        // TODO add your handling code here
        try
        {
            String id = cbId.getSelectedItem().toString();
            rs = stmt.executeQuery("select * from personalinfo where EmpId= '"+id+"'");
            while(rs.next())
            {
                txtName.setText(rs.getString(1));
                txtFather.setText(rs.getString(2));
                txtDOB.setText(rs.getString(3));
                txtSalary.setText(rs.getString(4));
                txtAddress.setText(rs.getString(5));
                txtPhone.setText(rs.getString(6));
                txtEmail.setText(rs.getString(7));
                txtDesg.setText(rs.getString(9));
                txtAdhar.setText(rs.getString(10));
                lblId.setText(id);
                txtJob.setText(rs.getString(12));
            }
        }
        catch(SQLException e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_btnFetchActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbEducation;
    private javax.swing.JComboBox<String> cbId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdhar;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDesg;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
